"""量能均线筛选策略默认参数。"""

MA20_TO_MA5_FACTOR = 0.91
MA5_TO_MA10_MIN_RATIO = 1.0
MA5_TO_MA10_MAX_RATIO = 1.3
MIN_SIGNAL_DAY_PCT_CHG = -3.0
MAX_SIGNAL_DAY_PCT_CHG = 4.8
DEFAULT_THRESHOLD = 1.15
DEFAULT_HISTORY_YEARS = 3
DEFAULT_PRE20_MAX_PCT = 20.0

# --this-week-hits / --last-week-hits：同股去重窗口（自然日）
HITS_PERIOD_DAYS = 7

# 日终跑批（如定时 16:00）：15:00 后信号日=日历当日；Baostock 未入库则重试等待
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 0
SIGNAL_DAY_BAOSTOCK_RETRIES = 15
SIGNAL_DAY_BAOSTOCK_RETRY_SECONDS = 60
